apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: zulake/payment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
