apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: zulake/payment-service:f54db7e8851aab5a7a0ddaf3d8ed28f218a1a1ea
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
        livenessProbe:
          httpGet:
            path: /system/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /system/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 20m
            ephemeral-storage: 1Gi
            memory: 128Mi
