apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-content-service
  template:
    metadata:
      labels:
        app: course-content-service
    spec:
      containers:
      - name: course-content-service
        image: zulake/course-content-service:2e412f8cc133120afcfe3bbc98b2e8320e6e253c
        imagePullPolicy: Always
        ports:
        - containerPort: 8200
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
