apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-content-service
  template:
    metadata:
      labels:
        app: course-content-service
    spec:
      containers:
      - name: course-content-service
        image: zulake/course-content-service:089559dd9bc18059ee796a4b86f00a6cdf6914ee
        imagePullPolicy: Always
        ports:
        - containerPort: 8200
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
