apiVersion: v1
kind: Service
metadata:
  name: course-content-service
spec:
  selector:
    app: course-content-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8200
  type: LoadBalancer
