apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: zulake/notification-service:089559dd9bc18059ee796a4b86f00a6cdf6914ee
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
