apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: zulake/notification-service:4e2fb960e82ff85a232c7f9eede8dee179a4fc0e
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/readiness
            port: 7000
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/liveness
            port: 7000
        resources:
          requests:
            cpu: 20m
            ephemeral-storage: 1Gi
            memory: 128Mi
