apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: zulake/user-service:2e412f8cc133120afcfe3bbc98b2e8320e6e253c
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/readiness
            port: 8000
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/liveness
            port: 8000
        resources:
          requests:
            cpu: 20m
            ephemeral-storage: 1Gi
            memory: 128Mi
