apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: zulake/user-service:a89cb587430de90a4f60fe86566ab021ca4584ba
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
        livenessProbe:
          httpGet:
            path: /system/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /system/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 20m
            ephemeral-storage: 1Gi
            memory: 128Mi
