apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: zulake/course-service:f54db7e8851aab5a7a0ddaf3d8ed28f218a1a1ea
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
