apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: zulake/course-service:089559dd9bc18059ee796a4b86f00a6cdf6914ee
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/readiness
            port: 8100
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/liveness
            port: 8100
        resources:
          requests:
            cpu: 20m
            ephemeral-storage: 1Gi
            memory: 128Mi
