apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: zulake/course-service:b542b2520f08f2b361cbb3427745a3e10e2ef0f0
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
