apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: zulake/course-service:a89cb587430de90a4f60fe86566ab021ca4584ba
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
